"use client";

import React from "react";
import { PageHeader } from "@/components/ui/page-header";
import { Panel } from "@/components/ui/panel";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Printer, ShieldCheck } from "lucide-react";
import { TableWrapper, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table-wrapper";

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Intelligence Report Dossier Generator"
        description="Generate audited, tamper-evident PDF intelligence dossiers powered by Catalyst SmartBrowz."
        badge={<Badge variant="accent">Catalyst SmartBrowz</Badge>}
        actions={
          <div className="flex items-center gap-2">
            <Button variant="secondary" icon={<Printer className="w-4 h-4" />}>
              Print Dossier
            </Button>
            <Button variant="primary" icon={<Download className="w-4 h-4" />}>
              Export Official PDF
            </Button>
          </div>
        }
      />

      <Panel title="Generated Intelligence Dossiers">
        <TableWrapper>
          <TableHeader>
            <TableRow>
              <TableHead>Dossier ID</TableHead>
              <TableHead>Target District / Scope</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Timestamp</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {[
              { id: "REP-2026-081", scope: "Bengaluru Urban Hotspot Assessment", author: "Inspector V. Patil", date: "2026-07-20 17:30 IST", status: "Audited & Sealed" },
              { id: "REP-2026-080", scope: "Mysuru Coastal Smuggling Brief", author: "Analyst R. Kumar", date: "2026-07-19 14:15 IST", status: "Ready" },
              { id: "REP-2026-079", scope: "Statewide Quarterly Crime Briefing", author: "SCRB Director Office", date: "2026-07-15 09:00 IST", status: "Archived" },
            ].map((row) => (
              <TableRow key={row.id}>
                <TableCell className="font-mono font-bold text-primary">{row.id}</TableCell>
                <TableCell className="font-medium text-white">{row.scope}</TableCell>
                <TableCell>{row.author}</TableCell>
                <TableCell className="font-mono">{row.date}</TableCell>
                <TableCell>
                  <Badge variant="success" size="sm">
                    <ShieldCheck className="w-3 h-3 mr-1" /> {row.status}
                  </Badge>
                </TableCell>
                <TableCell>
                  <Button variant="ghost" size="sm" icon={<FileText className="w-3.5 h-3.5" />}>
                    Download
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </TableWrapper>
      </Panel>
    </div>
  );
}
